version: '3'
services:
    backend:
        build: ./backend
        ports:
            - "9000:9000"
        volumes:
            - ./backend:/go/src/app
        depends_on: 
            - db
        env_file: env
    db:
        image: "postgres:12.2-alpine"
        ports: 
            - "5432:5432"
        volumes:
            - exercises-dbdata:/var/lib/postgresql/data
        env_file: env

volumes: 
    exercises-dbdata:
        external: true